# Generated by Django 2.2.1 on 2019-09-18 07:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import multipoll.models.fields.timestamp
import multipoll.models.pollbase


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalPoll',
            fields=[
                ('timestamp', multipoll.models.fields.timestamp.TimestampField(max_length=50, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=9)),
                ('question', models.CharField(max_length=200)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=99)),
            ],
            options={
                'ordering': ('timestamp',),
                'get_latest_by': 'timestamp',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FullApprovalVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_secret', models.CharField(max_length=11, null=True)),
                ('weights', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), default=multipoll.models.pollbase.default_options_inner, size=99)),
            ],
            options={
                'ordering': ('poll', 'user'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FullMultiVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_secret', models.CharField(max_length=11, null=True)),
                ('weights', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=multipoll.models.pollbase.default_options_inner, size=99)),
            ],
            options={
                'ordering': ('poll', 'user'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultiPoll',
            fields=[
                ('timestamp', multipoll.models.fields.timestamp.TimestampField(max_length=50, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=9)),
                ('question', models.CharField(max_length=200)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=99)),
            ],
            options={
                'ordering': ('timestamp',),
                'get_latest_by': 'timestamp',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartialApprovalVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.PositiveSmallIntegerField()),
                ('weights', models.BooleanField()),
            ],
            options={
                'ordering': ('poll', 'option', 'user'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartialMultiVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.PositiveSmallIntegerField()),
                ('weights', models.SmallIntegerField()),
            ],
            options={
                'ordering': ('poll', 'option', 'user'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'get_latest_by': 'name',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['name'], name='multipoll_u_name_a247f4_idx'),
        ),
        migrations.AddField(
            model_name='partialmultivote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partialvote_set', to='multipoll.MultiPoll'),
        ),
        migrations.AddField(
            model_name='partialmultivote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multipoll.User'),
        ),
        migrations.AddField(
            model_name='partialapprovalvote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partialvote_set', to='multipoll.ApprovalPoll'),
        ),
        migrations.AddField(
            model_name='partialapprovalvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multipoll.User'),
        ),
        migrations.AddIndex(
            model_name='multipoll',
            index=models.Index(fields=['timestamp'], name='multipoll_m_timesta_32e84d_idx'),
        ),
        migrations.AddField(
            model_name='fullmultivote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fullvote_set', to='multipoll.MultiPoll'),
        ),
        migrations.AddField(
            model_name='fullmultivote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multipoll.User'),
        ),
        migrations.AddField(
            model_name='fullapprovalvote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fullvote_set', to='multipoll.ApprovalPoll'),
        ),
        migrations.AddField(
            model_name='fullapprovalvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multipoll.User'),
        ),
        migrations.AddIndex(
            model_name='approvalpoll',
            index=models.Index(fields=['timestamp'], name='multipoll_a_timesta_9f51b6_idx'),
        ),
        migrations.AddIndex(
            model_name='partialmultivote',
            index=models.Index(fields=['poll'], name='multipoll_p_poll_id_24c743_idx'),
        ),
        migrations.AddConstraint(
            model_name='partialmultivote',
            constraint=models.UniqueConstraint(fields=('poll', 'option', 'user'), name='SinglePartialMultiVoteCopy'),
        ),
        migrations.AddIndex(
            model_name='partialapprovalvote',
            index=models.Index(fields=['poll'], name='multipoll_p_poll_id_6a3579_idx'),
        ),
        migrations.AddConstraint(
            model_name='partialapprovalvote',
            constraint=models.UniqueConstraint(fields=('poll', 'option', 'user'), name='SinglePartialApprovalVoteCopy'),
        ),
        migrations.AddIndex(
            model_name='fullmultivote',
            index=models.Index(fields=['poll'], name='multipoll_f_poll_id_6cba0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='fullmultivote',
            constraint=models.UniqueConstraint(fields=('poll', 'user'), name='SingleFullMultiVoteCopy'),
        ),
        migrations.AddIndex(
            model_name='fullapprovalvote',
            index=models.Index(fields=['poll'], name='multipoll_f_poll_id_b0880c_idx'),
        ),
        migrations.AddConstraint(
            model_name='fullapprovalvote',
            constraint=models.UniqueConstraint(fields=('poll', 'user'), name='SingleFullApprovalVoteCopy'),
        ),
    ]
