# Generated by Django 2.2.5 on 2019-09-19 09:05

import django.contrib.postgres.fields
from django.db import migrations, models
import multipoll.models.pollbase


class Migration(migrations.Migration):

    dependencies = [
        ('multipoll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullmultivote',
            name='weights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(null=True), default=multipoll.models.pollbase.default_options_inner, size=99),
        ),
        migrations.AlterField(
            model_name='partialmultivote',
            name='weights',
            field=models.SmallIntegerField(null=True),
        ),
    ]
