# Generated by Django 2.2.5 on 2019-09-19 17:18

import django.contrib.postgres.fields
from django.db import migrations, models
import multipoll.models.pollbase


class Migration(migrations.Migration):

    dependencies = [
        ('multipoll', '0002_allow_null_weights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullapprovalvote',
            name='weights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(null=True), default=multipoll.models.pollbase.default_options_inner, size=99),
        ),
        migrations.AlterField(
            model_name='partialapprovalvote',
            name='weights',
            field=models.BooleanField(null=True),
        ),
    ]
