# Generated by Django 2.2.1 on 2019-09-15 17:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options_inner', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), default=main.models.default_options_inner, size=99)),
                ('user_secret', models.CharField(max_length=11, null=True)),
            ],
            options={
                'ordering': ['poll', 'user'],
            },
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['poll', 'option']},
        ),
        migrations.RemoveConstraint(
            model_name='vote',
            name='Single Vote Copy',
        ),
        migrations.AlterField(
            model_name='poll',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=99),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=99),
        ),
        migrations.AlterUniqueTogether(
            name='poll',
            unique_together={('timestamp',)},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll', 'option', 'user')},
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['timestamp'], name='main_poll_timesta_dd97ef_idx'),
        ),
        migrations.AddField(
            model_name='completevote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Poll'),
        ),
        migrations.AddField(
            model_name='completevote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.AddIndex(
            model_name='completevote',
            index=models.Index(fields=['poll'], name='main_comple_poll_id_613aa0_idx'),
        ),
        migrations.AddConstraint(
            model_name='completevote',
            constraint=models.UniqueConstraint(fields=('poll', 'user'), name='SingleVoteCopy'),
        ),
    ]
