# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_polls_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='content',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='user',
        ),
        migrations.AddField(
            model_name='votes',
            name='option',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votes',
            name='users',
            field=models.CharField(default=[], max_length=1000),
            preserve_default=False,
        ),
    ]
