# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='timestamp',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
