apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: multipoll-postgres
  name: multipoll-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    io.kompose.service: multipoll-postgres
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: multipoll-postgres
  name: multipoll-postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: multipoll-postgres
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: multipoll-postgres
    spec:
      containers:
        - image: postgres
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          name: multipoll-postgres
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postresql/data/
              name: multipoll-postgres-claim
      restartPolicy: Always
      volumes:
      - name: multipoll-postgres-claim
        persistentVolumeClaim:
          claimName: multipoll-postgres-claim
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: multipoll-postgres-claim
  name: multipoll-postgres-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: multipoll
  name: multipoll
spec:
  ports:
  - name: "8020"
    port: 8020
    targetPort: 8020
  selector:
    io.kompose.service: multipoll
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: multipoll
  name: multipoll
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: multipoll
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: multipoll
    spec:
      containers:
        - name: multipoll
          image: localhost:32000/multipoll:latest
          ports:
          - containerPort: 8020
          env:
            - name: MPOLLS_DATABASE
              value: postgres
            - name: MPOLLS_DATABASE_NAME
              value: postgres
            - name: MPOLLS_DATABASE_PORT
              value: "5432"
            - name: MPOLLS_DATABASE_URL
              value: multipoll-postgres
            - name: MPOLLS_DATABASE_USERNAME
              value: postgres
            - name: MPOLLS_SLACK_SECRET
              valueFrom:
                secretKeyRef:
                  name: multipoll-secrets
                  key: MPOLLS_SLACK_SECRET
            - name: MPOLLS_SLACK_BOT_SECRET
              valueFrom:
                secretKeyRef:
                  name: multipoll-secrets
                  key: MPOLLS_SLACK_BOT_SECRET
            - name: MPOLLS_DEFAULT_CHANNEL
              valueFrom:
                secretKeyRef:
                  name: multipoll-secrets
                  key: MPOLLS_DEFAULT_CHANNEL 
            - name: MPOLLS_HOST
              valueFrom:
                secretKeyRef:
                  name: multipoll-secrets
                  key: MPOLLS_HOST
            - name: MPOLLS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: multipoll-secrets
                  key: MPOLLS_SECRET_KEY
            - name: MPOLLS_SLACK_VERIFIER
              valueFrom:
                secretKeyRef:
                  name: multipoll-secrets
                  key: MPOLLS_SLACK_VERIFIER
          command: [/bin/sh, -c]
          args:
            - python manage.py migrate && python manage.py
              runserver 0.0.0.0:8020
      restartPolicy: Always
status: {}
