name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: TAG=$(git rev-parse --short HEAD) docker-compose -f .docker/docker-compose.yml build
    - name: Check Flake8 compliance
      run: TAG=$(git rev-parse --short HEAD) docker-compose -f .docker/docker-compose.yml run multipoll sh -c 'pip install -r requirements.flake8.txt && MYPYPATH="" flake8 --format=pylint .'
    - name: Ensure Migrations are Up to Date 
      run: TAG=$(git rev-parse --short HEAD) docker-compose -f .docker/docker-compose.yml run multipoll python manage.py makemigrations --check
